name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: site
  cancel-in-progress: false

jobs:
  build-artifact:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@633bb92bc0aabcae06e8ea93b85aecddd374c402 # actions/setup-node@v4
        with:
          node-version: 25
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm exec turbo build

      - name: Upload artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # actions/upload-artifact@v6.0.0
        with:
          name: web
          path: dist
          if-no-files-found: error
          retention-days: 2
          include-hidden-files: true

  publish-site:
    name: publish github site
    runs-on: ubuntu-latest
    needs:
      - build-artifact

    steps:
      - name: Deploy to github pages
        uses: actions/configure-github-pages@983d7736d9b0ae728b81ab479565c72886d7745b # actions/configure-github-pages@v5.0.0
        with:
          enablement: true
